version: '3.8'

services:
  db:
    image: mysql
    container_name: taquilla
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: taquillaZoo
      MYSQL_USER: root
      MYSQL_PASSWORD: FazsodAjvaswMwG0o01W
    ports:
      - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    